---
- hosts: all
  tasks:
    - name: Debian and Ubuntu OS Upgrade
      ansible.builtin.apt:
        upgrade: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  tasks:
    - name: Arch Linux OS Upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: ansible_distribution == 'Archlinux'

      
